// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using cp2.Data;

#nullable disable

namespace cp2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("cp2.Models.Agencia", b =>
                {
                    b.Property<int>("IdAgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgencia"));

                    b.Property<string>("Cep")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmEndereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdAgencia");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("cp2.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<int?>("AgenciaIdAgencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("IdAgencia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmCliente")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("IdCliente");

                    b.HasIndex("AgenciaIdAgencia");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("cp2.Models.Contratacao", b =>
                {
                    b.Property<int>("IdContratacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContratacao"));

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DtSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ProdutoIdProduto")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdContratacao");

                    b.HasIndex("ClienteIdCliente");

                    b.HasIndex("ProdutoIdProduto");

                    b.ToTable("Contratacoes");
                });

            modelBuilder.Entity("cp2.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("NmProduto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("cp2.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("cp2.Models.Cliente");

                    b.Property<string>("Cpf")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("cp2.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("cp2.Models.Cliente");

                    b.Property<string>("Cnpj")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("cp2.Models.Emprestimo", b =>
                {
                    b.HasBaseType("cp2.Models.Produto");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TaxaJuros")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");
                });

            modelBuilder.Entity("cp2.Models.Cliente", b =>
                {
                    b.HasOne("cp2.Models.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaIdAgencia");

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("cp2.Models.Contratacao", b =>
                {
                    b.HasOne("cp2.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdCliente");

                    b.HasOne("cp2.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoIdProduto");

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
